// import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars = {
    tutorialSidebar: [
        {
            type: 'category',
            label: '入门',
            collapsed: false,
            items: ['getting-started/introduction', 'getting-started/comparison'],
        },
        {
            type: 'category',
            label: '指南',
            collapsed: false,
            items: [
                'guides/tutorial-tic-tac-toe',
                'guides/updating-state',
                'guides/immutable-state-and-merging',
                'guides/flux-inspired-practice',
                'guides/auto-generating-selectors',
                'guides/practice-with-no-store-actions',
                'guides/typescript',
                'guides/testing',
                'guides/event-handler-in-pre-react-18',
                'guides/maps-and-sets-usage',
                'guides/connect-to-state-with-url-hash',
                'guides/how-to-reset-state',
                'guides/initialize-state-with-props',
                'guides/slices-pattern',
                'guides/prevent-rerenders-with-use-shallow',
                'guides/ssr-and-hydration',
                'guides/nextjs',
            ],
        },
        {
            type: 'category',
            label: '集成',
            collapsed: false,
            items: ['integrations/immer-middleware', 'integrations/third-party-libraries', 'integrations/persisting-store-data'],
        },
        {
            type: 'category',
            label: '以前的版本',
            items: ['previous-versions/zustand-v3-create-context'],
        },
        {
            type: 'category',
            label: '迁移',
            items: ['migrations/migrating-to-v4', 'migrations/migrating-to-v5'],
        },
        {
            type: 'category',
            label: 'Apis',
            items: ['apis/create-store', 'apis/create-with-equality-fn', 'apis/create', 'apis/shallow'],
        },
        {
            type: 'category',
            label: 'Hooks',
            items: ['hooks/use-shallow', 'hooks/use-store-with-equality-fn', 'hooks/use-store'],
        },
        {
            type: 'category',
            label: '中间件',
            items: [
                'middlewares/combine',
                'middlewares/devtools',
                'middlewares/immer',
                'middlewares/persist',
                'middlewares/redux',
                'middlewares/subscribe-with-selector',
            ],
        },
    ],
};

export default sidebars;
// tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
